### ISSUE TITLE
3B-L3 block size mismatch w/ answer

### ISSUE THREAD

**Issue by pvphan** [pdvelez/CV-lecture-quizzes-python#5]
Really minor, but caught me off guard:
in `3B-L3/match_two_strips.py`, b = 100,
while in `3B-L3/answers/match_two_strips.py`, b = 80

**Comment by pdvelez** [comment]
Fixed in a536a91. I was also able to create images from a data set that matches the ones used in the quiz.

**Comment by pvphan** [comment]
Nice, thank you!
