### ISSUE TITLE
2A-L5 Answer out of sync with Student copy

### ISSUE THREAD

**Issue by DSchmidlin** [pdvelez/CV-lecture-quizzes-python#6]
The student version calculates gmag thusly:

gmag = np.sqrt(gx**2 + gy**2) / (4 * np.sqrt(2))

While the answer uses:

gmag = np.sqrt(gx**2 + gy**2)

This is causing the gradient to be all zeros

**Comment by pdvelez** [comment]
Fixed in fa12c06
